---
galaxy_info:
  author: Roderik van der Veer - Modified by Vid
  description: Ansible profile role for developers
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - vid.superlumic-computername
  - vid.superlumic-cli
  - vid.superlumic-homebrew
  - vid.superlumic-php
  #- vid.superlumic-sublimetext
  - vid.superlumic-node
  - vid.superlumic-vim
  - profile-all
